def cambia_letras(animal, file):
    file.write(animal)
    file.write("\n")
    animal = animal.lower()
    file.write(animal)
    file.write("\n")
    animal = animal.upper()
    file.write(animal)
    file.write("\n")
    animal = animal.capitalize()     
    file.write(animal)
    file.write("\n")
    animal = animal.title()
    file.write(animal)
    file.write("\n")
    animal = animal.swapcase()
    file.write(animal)
    file.write("\n")